defaults:
  - /forward_process: block_masked
  - /sampling: block
  - /noise: log-linear

_target_: discrete_diffusion.algorithms.block_trainer.BlockTrainer
name: block_masked
forward_process_name: masked
parameterization: subs
time_conditioning: False
T: 0
loss_type: elbo
ignore_bos: True
shift_loss_targets: False
